- name: Create Garage directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ data_dir }}"
    - "{{ data_dir }}/meta"
    - "{{ data_dir }}/data"

- name: Create Garage app directories
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Render docker-compose
  template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ app_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Render config
  template:
    src: templates/config/garage.toml.j2
    dest: "{{ app_dir }}/config/garage.toml"
    mode: '0644'
